 export const BasketballData = [{
         id: 1,
         title: "Date",
         name: "date",
         placeholder: "15 November 2022",
         backgroundColor: "#ebeff8",
     },
     {
         id: 2,
         title: "Start Time",
         name: "startTime",
         placeholder: "12.00 Eastern",
     },
     {
         id: 3,
         title: "HOME Team",
         name: "homeTeam",
         placeholder: "Los Angeles",
         backgroundColor: "#ebeff8",
     },
     {
         id: 4,
         title: "Coach",
         name: "hCoach",
         placeholder: "Jim Wood",
     },
     {
         id: 5,
         title: "WON",
         name: "hWon",
         placeholder: "83",
         backgroundColor: "#ebeff8",
     },
     {
         id: 6,
         title: "LOST",
         name: "hLost",
         placeholder: "55",
     },
     {
         id: 7,
         title: "Win %",
         name: "hWin",
         placeholder: "62%",
         backgroundColor: "#ebeff8",
     },
     {
         id: 8,
         title: "Last 10",
         name: "hLast10",
         placeholder: "8-2",
     },
     {
         id: 9,
         title: "Conference",
         name: "hConference",
         placeholder: "Wetern",
         backgroundColor: "#ebeff8",
     },
     {
         id: 10,
         title: "Division Standing",
         name: "hDivisionStanding",
         placeholder: "2",
     },
     {
         id: 11,
         title: "AWAY Team",
         name: "awayTeam",
         placeholder: "Florida ",
         backgroundColor: "#ebeff8",
     },
     {
         id: 12,
         title: "Coach",
         name: "aCoach",
     },
     {
         id: 13,
         title: "WON",
         name: "aWon",

         backgroundColor: "#ebeff8",
     },
     {
         id: 14,
         title: "LOST",
         name: "aLost",
     },
     {
         id: 15,
         title: "Win %",
         name: "aWin",

         backgroundColor: "#ebeff8",
     },
     {
         id: 16,
         title: "Last 10",
         name: "aLast10",
     },
     {
         id: 17,
         title: "Conference",
         name: "aConference",
         backgroundColor: "#ebeff8",
     },
     {
         id: 17,
         title: "Division Standing",
         name: "aDivisionStanding",
     },
 ];