export const UFCData = [
  {
    id: 1,
    title: "Event Name",
    name: "eventName",
    placeholder: "Type",
    backgroundColor: "#004267",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 2,
    title: "Component Path",
    name: "componentPath",
    placeholder: "Path",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 3,
    title: "Time",
    name: "time",
    placeholder: "00:00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 4,
    title: "Date",
    name: "date",
    placeholder: "00/00/00",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 5,
    name: "competitor1",
    title: "Competitor 1",
    placeholder: "Amount",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 6,
    title: "Record",
    name: "c1record",
    placeholder: "Amount",
  },
  {
    id: 7,
    title: "Height",
    name: "c1height",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 8,
    title: "Weight",
    name: "c1weight",
    placeholder: "Amount",
  },
  {
    id: 9,
    title: "Reach",
    name: "c1reach",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 10,
    title: "Stance",
    name: "c1stance",
    placeholder: "Amount",
  },
  {
    id: 11,
    title: "Age",
    name: "c1age",
    placeholder: "Amount",
    backgroundColor: "#ebeff8",
  },
  {
    id: 12,
    title: "Rank",
    name: "c1rank",
    placeholder: "Amount",
  },

  {
    id: 13,
    name: "competitor2",
    title: "Competitor ",
    placeholder: "Amount",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 14,
    title: "Record",
    name: "c2record",
    placeholder: "Amount",
  },
  {
    id: 15,
    title: "Height",
    name: "c2height",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 16,
    title: "Weight",
    name: "c2weight",
    placeholder: "Amount",
  },
  {
    id: 17,
    title: "Reach",
    name: "c2reach",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 18,
    title: "Stance",
    name: "c2stance",
    placeholder: "Amount",
  },
  {
    id: 19,
    title: "Age",
    name: "c2age",
    placeholder: "Amount",
    backgroundColor: "#ebeff8",
  },
  {
    id: 20,
    title: "Rank",
    name: "c2rank",
    placeholder: "Amount",
  },
];
