  export const TennisData = [{
          id: 1,
          title: "Turned Pro",
          name: "turnedPro1",
          placeholder: "2003",
          backgroundColor: "#ebeff8",
      },
      {
          id: 2,
          title: "Height",
          name: "height1",
          placeholder: "188cm",
      },
      {
          id: 3,
          title: "Weight",
          name: "weight1",
          placeholder: "77kg",
          backgroundColor: "#ebeff8",
      },
      {
          id: 4,
          title: "PLAYS",
          name: "plays1",
          placeholder: "Right Handed",
      },
      {
          id: 5,
          title: "Age",
          name: "age1",
          placeholder: "2519",
          backgroundColor: "#ebeff8",
      },
      {
          id: 6,
          title: "Seasons",
          name: "seasons1",
          placeholder: "88",
      },
      {
          id: 7,
          title: "Country",
          name: "country1",
          placeholder: "03",
          backgroundColor: "#ebeff8",
      },
      {
          id: 8,
          title: "Titles",
          name: "titles1",
          placeholder: "2003",
      },
      {
          id: 9,
          title: "PTA WORLD RANK",
          name: "ptaWorldRank1",
          placeholder: "188cm",
          backgroundColor: "#ebeff8",
      },
      {
          id: 10,
          title: "Turned Pro",
          name: "turnedPro2",
          placeholder: "77kg",
      },
      {
          id: 11,
          title: "Height",
          name: "height2",
          placeholder: "Right Handed",
          backgroundColor: "#ebeff8",
      },
      {
          id: 12,
          title: "Weight",
          name: "weight2",
          placeholder: "25",
      },
      {
          id: 13,
          title: "PLAYS",
          name: "plays2",
          placeholder: "19",
          backgroundColor: "#ebeff8",
      },
      {
          id: 14,
          title: "Age",
          name: "age2",
          placeholder: "Serbia",
      },
      {
          id: 15,
          title: "Seasons",
          name: "seasons2",
          placeholder: "88",
          backgroundColor: "#ebeff8",
      },
      {
          id: 16,
          title: "Country",
          name: "country2",
          placeholder: "03",
      },
      {
          id: 17,
          title: "Titles",
          name: "titles2",
          placeholder: "Serbia",
          backgroundColor: "#ebeff8",
      },
      {
          id: 17,
          title: "PTA WORLD RANK",
          name: "ptaWorldRank2",
          placeholder: "88",
      },
  ];