export const FootballData = [
  {
    id: 1,
    title: "Event Name",
    name: "eventName",
    placeholder: "Type",
    backgroundColor: "#004267",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 2,
    title: "Component Path",
    name: "componentPath",
    placeholder: "Path",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 3,
    title: "Date",
    name: "date",
    placeholder: "00:00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 4,
    title: "Start Time GMT",
    name: "stGMT",
    placeholder: "00/00/00",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 5,
    title: "HOME Team",
    name: "homeTeam",
    placeholder: "Type",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 6,
    title: "Record",
    name: "hRecord",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 7,
    title: "Home Record",
    name: "hHomeRecord",
    backgroundColor: "#ebeff8",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 8,
    title: "Away Record",
    name: "hAwayRecord",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 9,
    title: "GF GA GD",
    name: "hGFGAGD",
    backgroundColor: "#ebeff8",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 10,
    title: "Coach",
    name: "hCoach",
    placeholder: "Type",
  },
  {
    id: 11,
    title: "League Position",
    name: "hLeaguePosition",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 12,
    title: "Fifa Club Ranking",
    name: "hFifaClubRanking",
    placeholder: "Amount",
  },
  {
    id: 13,
    name: "awayTeam",
    title: "AWAY Team",
    placeholder: "Type",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 14,
    title: "Record",
    name: "aRecord",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 15,
    title: "Home Record",
    name: "aHomeRecord",
    backgroundColor: "#ebeff8",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 16,
    title: "Away Record",
    name: "aAwayRecord",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 17,
    title: "GF GA GD",
    name: "aGFGAGD",
    backgroundColor: "#ebeff8",
    placeholder: "00-00-00",
    color_1: "#000000",
  },
  {
    id: 18,
    title: "Coach",
    name: "aCoach",
    placeholder: "Type",
  },
  {
    id: 19,
    title: "League Position",
    name: "aLeaguePosition",
    placeholder: "Amount",
    backgroundColor: "#ebeff8",
  },
  {
    id: 20,
    title: "Fifa Club Ranking",
    name: "aFifaClubRanking",
    placeholder: "Amount",
  },
];
