export const PoliticsData = [{
    id: 1,
    title: "Event Name",
    name: "eventName",
    placeholder: "Type",
    backgroundColor: "#004267",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 2,
    title: "Component Path",
    name: "componentPath",
    placeholder: "Path",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 3,
    title: "Time",
    name: "time",
    placeholder: "00:00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 4,
    title: "Date",
    name: "date",
    placeholder: "00/00/00",
    color: "#9b9b9b",
    color_1: "#000000",
  },
];