export const BitcoinData = [{
    id: 1,
    title: "Event Name",
    name: "eventName",
    placeholder: "Type",
    backgroundColor: "#004267",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 2,
    title: "Pool Start Date",
    name: "poolstartdate",
    placeholder: "00/00/00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 3,
    title: "Pool Start Time",
    name: "poolstarttimes",
    placeholder: "00:00",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 4,
    name: "poolfinishdate",
    title: "Pool Finish Date",
    placeholder: "00/00/00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 5,
    title: "Pool Finish Time",
    name: "poolfinishtime",
    placeholder: "Amount",
  },
  {
    id: 6,
    title: "Starting Market Price $",
    name: "smp",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 7,
    title: "24 Hour Trading Vol $",
    name: "hourTradingVol24",
    placeholder: "Amount",
  },
  {
    id: 8,
    title: "24h Low / 24 High $",
    name: "lowandhigh24",
    backgroundColor: "#ebeff8",
    placeholder: "Amount",
  },
  {
    id: 9,
    title: "7d Low / 7d High $",
    name: "Lowhigh7d",
    placeholder: "Amount",
  },
  {
    id: 10,
    title: "Price Range 1",
    name: "priceRange1",
    placeholder: "Amount",
    backgroundColor: "#ebeff8",
  },
  {
    id: 11,
    title: "Price Range 2",
    name: "priceRange2",
    placeholder: "Amount",
  },
  {
    id: 12,
    title: "Price Range 3",
    name: "priceRange3",
    placeholder: "Amount",
    backgroundColor: "#ebeff8",
  },
  {
    id: 13,
    title: "Price Range 4",
    name: "priceRange4",
    placeholder: "Amount",
  },
];