export const BoxingData = [{
        id: 1,
        title: "Time",
        name: "time",
        placeholder: "03.00",
        backgroundColor: "#ebeff8",
    },
    {
        id: 2,
        title: "DIVISION",
        name: "division",
        placeholder: "Middleweight",
    },
    {
        id: 3,
        title: "Date",
        name: "date",
        placeholder: "Tuesday 15 October",
        backgroundColor: "#ebeff8",
    },
    {
        id: 4,
        title: "Player 1",
        name: "player1",
        placeholder: "Canello Alveraz",
    },
    {
        id: 5,
        title: "BORN",
        name: "p1born",
        placeholder: "Jan 17 1987 (35)",
        backgroundColor: "#ebeff8",
    },
    {
        id: 6,
        title: "Height",
        name: "p1Height",
        placeholder: "6` 3`` , 190cm",
    },
    {
        id: 7,
        title: "KO's",
        name: "p1KOs",
        placeholder: "13",
        backgroundColor: "#ebeff8",
    },
    {
        id: 8,
        title: "Country",
        name: "p1Country",
        placeholder: "Mexico",
    },
    {
        id: 9,
        title: "WBC RANKING",
        name: "p1WBCRanking",
        placeholder: "2",
        backgroundColor: "#ebeff8",
    },
    {
        id: 10,
        title: "STANCE",
        name: "p1Stance",
        placeholder: "Orthodox",
    },
    {
        id: 11,
        title: "Player 2",
        name: "player2",
        placeholder: "Jon Jones ",
        backgroundColor: "#ebeff8",
    },
    {
        id: 12,
        title: "BORN",
        name: "p2born",
    },
    {
        id: 13,
        title: "Height",
        name: "p2Height",
        backgroundColor: "#ebeff8",
    },
    {
        id: 14,
        title: "KO's",
        name: "p2KOs",
    },
    {
        id: 15,
        title: "Country",
        name: "p2Country",
        backgroundColor: "#ebeff8",
    },
    {
        id: 16,
        title: "Titles",
        name: "titles",
    },
    {
        id: 17,
        title: "WBC Ranking",
        name: "p2WBCRanking",
        backgroundColor: "#ebeff8",
    },
    {
        id: 17,
        title: "Stance",
        name: "p2Stance",
    },
];