export const CricketData = [{
    id: 1,
    title: "Event Name",
    name: "eventName",
    placeholder: "Type",
    backgroundColor: "#004267",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 2,
    title: "Component Path",
    name: "componentPath",
    placeholder: "Path",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 3,
    title: "Date",
    name: "date",
    placeholder: "00:00",
    backgroundColor: "#ebeff8",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 4,
    title: "Time",
    name: "time",
    placeholder: "00/00/00",
    color: "#9b9b9b",
    color_1: "#000000",
  },
  {
    id: 5,
    title: "Team 1",
    name: "team1",
    placeholder: "Type",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 6,
    title: "ODI matches",
    name: "t1OdiMatches",
  },
  {
    id: 7,
    title: "Victories",
    name: "t1Victories",
    backgroundColor: "#ebeff8",
  },
  {
    id: 8,
    title: "Defeats",
    name: "t1Defeats",
  },
  {
    id: 9,
    title: "Ties",
    name: "t1Ties",
    backgroundColor: "#ebeff8",
  },
  {
    id: 10,
    title: "W/L ratio",
    name: "t1WLRatio",
  },
  {
    id: 11,
    title: "Overall winning %",
    name: "t1OverAllWin",
    backgroundColor: "#ebeff8",
  },
  {
    id: 12,
    title: "WCB Ranking",
    name: "t1WCBRank",
  },
  {
    id: 13,
    title: "Team 2",
    name: "team2",
    placeholder: "Type",
    backgroundColor: "#00659D",
    color: "#FFFFFF",
    color_1: "#FFFFFF",
  },
  {
    id: 14,
    title: "ODI matches",
    name: "t2OdiMatches",
  },
  {
    id: 15,
    title: "Victories",
    name: "t2Victories",
    backgroundColor: "#ebeff8",
  },
  {
    id: 16,
    title: "Defeats",
    name: "t2Defeats",
  },
  {
    id: 17,
    title: "Ties",
    name: "t2Ties",
    backgroundColor: "#ebeff8",
  },
  {
    id: 18,
    title: "W/L ratio",
    name: "t2WLRatio",
  },
  {
    id: 19,
    title: "Overall winning %",
    name: "t2OverAllWin",
    backgroundColor: "#ebeff8",
  },
  {
    id: 20,
    title: "WCB Ranking",
    name: "t2WCBRank",
  },
];