 export const snookerData1 = [{
         id: 1,
         player: "Player1",
         username: "Sevi Ballesteros",
         name: "player1",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 2,
         player: "Player2",
         username: "Sevi Ballesteros",
         name: "player2",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 3,
         player: "Player3",
         username: "Sevi Ballesteros",
         name: "player3",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 4,
         player: "Player4",
         name: "player4",
     },
     {
         id: 5,
         player: "Player5",
         name: "player5",

         backgroundColor: "#ebeff8",
     },
     {
         id: 6,
         player: "Player6",
         name: "player6",
     },
     {
         id: 7,
         player: "Player7",
         name: "player7",
         backgroundColor: "#ebeff8",
     },
     {
         id: 8,
         player: "Player8",
         name: "player8",
     },
     {
         id: 9,
         player: "Player9",
         name: "player9",
         backgroundColor: "#ebeff8",
     },
     {
         id: 10,
         player: "Player10",
         name: "player10",
     },
     {
         id: 11,
         player: "Player11",
         name: "player11",
         backgroundColor: "#ebeff8",
     },
     {
         id: 12,
         player: "Player12",
         name: "player12",
     },
     {
         id: 13,
         player: "Player13",
         name: "player13",
         backgroundColor: "#ebeff8",
     },
     {
         id: 14,
         player: "Player14",
         name: "player14",
     },
     {
         id: 15,
         player: "Player15",
         backgroundColor: "#ebeff8",
         name: "player15",
     },
 ];
 export const snookerData2 = [{
         id: 16,
         player: "Player16",
         username: "Sevi Ballesteros",
         name: "player16",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 17,
         player: "Player17",
         username: "Sevi Ballesteros",
         name: "player17",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 18,
         player: "Player18",
         username: "Sevi Ballesteros",
         name: "player18",
         country: "ES",
         rank: "1",
         backgroundColor: "#ebeff8",
     },
     {
         id: 19,
         player: "Player19",
         name: "player19",
     },
     {
         id: 20,
         player: "Player20",
         name: "player20",
         backgroundColor: "#ebeff8",
     },
     {
         id: 21,
         player: "Player21",
         name: "player21",
     },
     {
         id: 22,
         player: "Player22",
         name: "player22",
         backgroundColor: "#ebeff8",
     },
     {
         id: 23,
         player: "Player23",
         name: "player23",
     },
     {
         id: 24,
         player: "Player24",
         name: "player24",
         backgroundColor: "#ebeff8",
     },
     {
         id: 25,
         player: "Player25",
         name: "player25",
     },
     {
         id: 26,
         player: "Player26",
         name: "player26",
         backgroundColor: "#ebeff8",
     },
     {
         id: 27,
         player: "Player27",
         name: "player27",
     },
     {
         id: 28,
         player: "Player28",
         name: "player28",
         backgroundColor: "#ebeff8",
     },
     {
         id: 29,
         player: "Player29",
         name: "player29",
     },
     {
         id: 30,
         player: "Player30",
         name: "player30",
         backgroundColor: "#ebeff8",
     },
 ];