  export const SoccerData = [{
          id: 1,
          title: "Date",
          name: "date",
          placeholder: "15 November 2022",
          backgroundColor: "#ebeff8",
      },
      {
          id: 2,
          title: "Start Time GMT",
          name: "startTimeGMT",
          placeholder: "20:00",
      },
      {
          id: 3,
          title: "HOME Team",
          name: "homeTeam",
          placeholder: "Manchester United",
          backgroundColor: "#ebeff8",
      },
      {
          id: 4,
          title: "Record",
          name: "record",
          placeholder: "26-6-4",
      },
      {
          id: 5,
          title: "Home Record",
          name: "homeRecord",
          placeholder: "26-6-4",
          backgroundColor: "#ebeff8",
      },
      {
          id: 6,
          title: "Away Record",
          name: "awayRecord",
          placeholder: "26-6-4",
      },
      {
          id: 7,
          title: "GF GA GD",
          name: "GFGAGD",
          placeholder: "16-8-8",
          backgroundColor: "#ebeff8",
      },
      {
          id: 8,
          title: "Coach",
          name: "coach",
          placeholder: "JImm Tomlinson",
      },
      {
          id: 9,
          title: "League Position",
          name: "leaguePosition",
          placeholder: "3",
          backgroundColor: "#ebeff8",
      },
      {
          id: 10,
          title: "Fifa Club Ranking",
          name: "fifaClubRanking",
          placeholder: "11",
      },
      {
          id: 11,
          title: "Away Team",
          name: "awayTeam",
          placeholder: "Liverpool",
          backgroundColor: "#ebeff8",
      },
      {
          id: 12,
          title: "Record",
          name: "aRecord",
          placeholder: "26-6-4",
      },
      {
          id: 13,
          title: "Home Record",
          name: "ahomeRecord",
          placeholder: "26-6-4",
          backgroundColor: "#ebeff8",
      },
      {
          id: 14,
          title: "Away Record",
          name: "aAwayRecord",
          placeholder: "26-6-4",
      },
      {
          id: 15,
          title: "GF GA GD",
          name: "aGFGAGD",
          placeholder: "16-8-8",
          backgroundColor: "#ebeff8",
      },
      {
          id: 16,
          title: "Coach",
          name: "aCoach",
          placeholder: "Jon Jones",
      },
      {
          id: 17,
          title: "League Position",
          name: "aleaguePosition",
          placeholder: "1",
          backgroundColor: "#ebeff8",
      },
      {
          id: 17,
          title: "Fifa Club Ranking",
          name: "afifaClubRanking",
          placeholder: "2",
      },
  ];